### ISSUE TITLE
Kotlin 1.6

### ISSUE THREAD

**Issue by erickskrauch** [alvr/alpine-android#17]
Hi. Is it possible to upgrade to Kotlin 1.6?

**Comment by alvr** [comment]
Hi,

to update Kotlin you should do it in your project's dependencies (build.gradle or build.gradle.kts), like in [this project](https://github.com/android/architecture-samples/blob/6f247c00e08545b3a30cdc67437ef229d14b3ad1/build.gradle#L2).

**Comment by erickskrauch** [comment]
Yes, but the problem is that the version of Kotlin supplied inside the images is currently `1.4.32`, i.e. when `1.6.x` is required, the project just won't build :(

**Comment by alvr** [comment]
These images don't include Kotlin compiler, maybe it's the version bundled with Gradle. Also Gradle is not included in the images, the version specified in the wrapper is used instead.

![image](https://user-images.githubusercontent.com/217315/158069296-59cdc8eb-aabd-4c0a-b810-16142467c81b.png)
![image](https://user-images.githubusercontent.com/217315/158069302-e8bf1618-f423-428c-8804-ff557c3fcd7f.png)
![image](https://user-images.githubusercontent.com/217315/158069309-4c767af4-4fbd-4db1-8a90-476ceab0319f.png)
