### ISSUE TITLE
JDK11 - Gradle daemon takes around half an hour to start.

### ISSUE THREAD

**Issue by cah-jayakumar-asokan** [alvr/alpine-android#18]
Hello - 

Docker tag: android-31-jdk11
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip

Issues - in our CICD Pipeline, we are using the "alpine-android" docker image. Recently we updated our Docker image to support jdk11 we are seeing this issue. Any help would be really helpful and much appreciated.

Thanks in advance.

**Comment by alvr** [comment]
Hi @cah-jayakumar-asokan,

I did some tests in differents CI using `android-31-jdk11` and when executing `./gradlew buildDebug` on [this](https://github.com/skydoves/Pokedex) project, I get an average time of 6 minutes. Can you try a different version? v2022.04.26 updates the JVM and Alpine.
