### ISSUE TITLE
add ssh support please and plz

### ISSUE THREAD

**Issue by aplha98** [alvr/alpine-android#26]
error: cannot run ssh: No such file or directory
fatal: unable to fork

Failed to clone 'apiplatform' a second time, aborting

**Comment by G00fY2** [comment]
If you need additional dependencies (which are not necessary/required for building Android projects) why don't you just install them? We e.g. run this when setting up the environment:
`apk --no-cache add git openssh-client`

**Comment by aplha98** [comment]
git sub modules

**Comment by ArcherEmiya05** [comment]
We are having this issue too, we get ` error: cannot run ssh: No such file or directory` when cloning a submodule which is a part of our pipeline steps. Any alternative solution? Thanks

**Comment by aplha98** [comment]
write down the git command that you are using

**Comment by alvr** [comment]
Package is added in [v2023.09.10](https://github.com/alvr/alpine-android/releases/tag/v2023.09.10).
