### ISSUE TITLE
JDK 19?

### ISSUE THREAD

**Issue by emartynov** [alvr/alpine-android#29]
I was at Droidcon UK, and there was mention that an upgrade to JDK 19 makes a noticeable build improvement. 
Do you have any plans for JDK 19?

I'm also kind of person who usually uses the latest JDK possible - Do you have thoughts about pointing the latest image to the latest JDK?

**Comment by G00fY2** [comment]
My opinion: Latest Android Studio is shipping JDK 17 too. Also people usually tend to use LTS JDK versions on Android. This would be JDK 21 which will only run with AGP 8.3.0-alpha03 and newer: https://issuetracker.google.com/issues/294137077

This also requires [Gradle 8.5+](https://docs.gradle.org/8.5-rc-1/userguide/compatibility.html) which is currently RC.

JDK 19 sounds a bit random to me. I would expect a new release with Java 21 LTS as soon as AGP 8.3 and Gradle 8.5 went stable.

**Comment by G00fY2** [comment]
> JDK 19 is not random for me.
I meant random in that sense that is neither the latest available version (JDK 21), nor the latest version that can be used to build with current stable AGP 8.1 (JDK 20).

> And, I don't write any Java code the LTS for me is not important and I believe Gradle, AGP and KGP just catch up as soon as possible.
I know that you can use newer JDK versions.
But at least Google jumped in their docs and their embedded JDK by the LTS versions:
- pre Android Studio 4.2 JDK 8
- Android Studio 4.2+ JDK 11
- Android Studio Flamingo JDK 17

**Comment by G00fY2** [comment]
Btw AGP 8.2.1 was released. So we can now use JDK 21 LTS with stable AGP.

**Comment by alvr** [comment]
JDK21 support is added in [v2024.01.05](https://github.com/alvr/alpine-android/releases/tag/v2024.01.05). I skipped JDK19 because is EOL.
