### ISSUE TITLE
Tagging versions?

### ISSUE THREAD

**Issue by Macarse** [alvr/alpine-android#5]
Hey!

With today's update, one of my pipelines broke because I was using an old Gradle wrapper version not compatible with java 11.

Is there any chance you can start tagging versions so users can go to an old version if necessary?

Thanks!

**Comment by alvr** [comment]
New versions, starting with v2021.01.01, will have a specific tag. Check the [versioning](https://github.com/alvr/alpine-android#versioning) part for more info.
